// CICLO FOR
/**
 * Este funciona de primero utilizando FOR (AQUI VA TODO LO DE ABAJO){CODIGO PARA EL FOR}
 * DENTRO DE LOS PARENTESIS SE UBICAN 3 PARTES SEPARADAS POR ;
 * 1.- EL 'INICIALIZADOR' QUE ES LA DECLARACION DE UNA VARIABLE QUE NOS SIRVE PARA CONTAR LAS ITERACIONES
 * 2.- LA CONDICION QUE SE DEBE SEGUIR PARA EL FUNCIONAMIENTO DEL CICLO
 * 3.- EL PARAMETRO QUE AUMENTA O DISMINUYE EL VALOR DE LA VARIABLE CONTADOR DEL CICLO
 */
//-------------------------------------------//
/**
 * PARA ESTE CASO
 * PRIMERO DECLARAMOS EN LA PRIMERA PARTE QUE NUESTRA VARIABLE i TIENE VALOR 2
 * LUEGO EN LA SEGUNDA PARTE COLOCAMOS NUESTRA CONDICION LA CUAL DICE QUE MIENTRAS i < 6 SEGUIRA EL CICLO
 * Y EN LA TERCERA PARTE COLOCAMOS EL AUMENTO POR CICLO EN ESTE CASO i++ (ESTO INDICA QUE i VA A AUMENTAR EN 1 POR CICLO)
 * LUEGO EN NUESTRA PORCION DE CODIGO QUE OCURRE DENTRO DEL CICLO 
 * AL PREGUNTAR SI EL MODULO DE i EN BASE 2 ES 0 ES DECIR SI ES UN NUMERO PAR
 * SE IMPRIMIRA LOS NUMERO PARES QUE EXISTAN HASTA LLEGAR AL NUMERO MAXIMO DE LA CONDICION
 */

for (let i = 2; i < 6; i++){
    if (i % 2 == 0){
        console.log(`Numero par: ${i}`); // ESTO DEBERIA MOSTRA HASTA EL NUMERO 4 YA QUE EL 6 NO SE CUENTA DENTRO DEL CICLO
    }
}

/** CICLO FOR OF
 * ESTE CICLO FOR FUNCIONA PARA ITERAR ARREGLOS
 * YA QUE LO QUE HACEMOS EN ESTE ES DECLARAR UNA VARIABLE QUE VA A TOMAR EL 
 * ELEMENTO DE UNA LISTA EN ESA ITERACION Y REALIZARA EL CONTENIDO DEL FOR EN BASE A ESE ELEMENTO
 * HASTA COMPLETAR EL RANGO DE ELEMENTOS QUE CONTENGA LA LISTA
 * 
 */


//EN ESTE CASO LA VARIABLE ANIMAL TOMA UN ELEMENTO DE LA LISTA Y LO IMPRIME EN PANTALLA EN CADA ITERACION

let animales = ["Cerdo", "Caballo", "Vaca", "Oveja"]
for (let animal of animales){
    console.log(animal);
}

/** CICLO FOR IN
 * ESTE FUNCIONA PARA ACCEDER A LAS ATRIBUTOS DE UN OBJETO o DICCIONARIO DE PYTHON
 */
let user = {
    id: 1,
    nombre: "Juan",
    edad: 32
};

for (let atributo in user){
    console.log(`${atributo}: ${user[atributo]}`)
};